config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # root to: 'lists#index'
  # resources :lists, only: [:create, :new, :index, :show] do
  #   resources :bookmarks, only: [:create, :new]
  # end

  root to: 'lists#index'
  resources :lists, except: [:edit, :update] do
    resources :bookmarks, only: [:create, :new]
  end
  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true
  validates :title, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  before_action :set_bookmark, only: :destroy
  before_action :set_list, only: [:new, :create]

  def new
    # @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    # @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    # No need for app/views/restaurants/destroy.html.erb
    redirect_to lists_path, status: :see_other
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
  <h1>Bookmarks</h1>
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment, placeholder: 'Enter a comment about the movie' %>
    <%= f.association :movie, prompt: "Select a movie", input_html: {data: { controller: "tom-select"}} %>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>
</div>

<div class="container">
  <h1>New Bookmark</h1>
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie, collection: Movie.all  %>
    <%= f.submit %>
  <% end %>
  <%= link_to "Back to all lists", lists_path, class: "btn btn-primary"  %>
</div>

app/views/bookmarks/show.html.erb
<h1><%= @list.name %></h1>
<div>
  <% @list.bookmarks.each do |bookmark| %>
  <div class="mb-2">
    <h2><%= bookmark.movie.title %></h2>
    <i><%= bookmark.movie.rating %></i>
    <h4><%= bookmark.movie.overview %></h4>
    <p><%= bookmark.comment %></p>
    <%= link_to "Delete",
      bookmark_path(bookmark),
      class: "btn btn-primary",
      data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
    %>
  </div>
  <% end %>
</div>

<p>
<%= link_to "Delete",
  task_path(@task),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1> Movie lists</h1>
<h2> <%= link_to "create a movie list", new_list_path %></h2>
<ul>
  <% @lists.each do |list| %>
    <li>
      <%= link_to list.name, list_path(list) %>
    </li>
  <% end %>
</ul>
<%= cl_image_tag("cxbtkhxwlqq4ir6vspas",
      width: 400, height: 300, crop: :fill) %>

app/views/lists/new.html.erb
<div class="container">
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%# <%= f.association :bookmark %>
  <%# <%= f.association :movies %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>
<%# <%= link_to, %> %>
</div>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>
<div>
  <% @list.bookmarks.each do |bookmark| %>
  <div class="mb-2">
    <h2><%= bookmark.movie.title %></h2>
    <i><%= bookmark.movie.rating %></i>
    <h4><%= bookmark.movie.overview %></h4>
    <p><%= bookmark.comment %></p>
    <%= link_to "Delete",
      bookmark_path(bookmark),
      class: "btn btn-primary",
      data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
    %>
  </div>
  <% end %>
</div>
<%= link_to "Back to all lists", lists_path, class: "btn btn-primary"  %>
<%= link_to "Create a bookmark", new_list_bookmark_path(@list), class: "btn btn-primary"  %>